on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
name: Soar Scanner
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
  # You may pin to the exact commit or the version.
  # uses: SonarSource/sonarcloud-github-action@5875562561d22a34be0c657405578705a169af6c
      uses: SonarSource/sonarcloud-github-action@v1.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        #projectBaseDir: ${{ github.workspace }}
        args: >
          -Dsonar.organization=anildevsecops
          -Dsonar.projectKey=anildevsecops
      #with:
    # Additional arguments to the sonarcloud scanner
        #args: # optional
    # Set the sonar.projectBaseDir analysis property
        #projectBaseDir: # optional, default is .
